-- BYTE BACK 2단계 학습용 Supabase 테이블 구조
-- 실제 학생 자료와 서버 전용 키는 이 파일에 넣지 않는다.
-- 가상 메모 본문은 Supabase SQL Editor에서 옮기고 Git 최신 파일에는 남기지 않는다.

create table if not exists public.memos (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  owner_id uuid,
  created_at timestamptz default now()
);

alter table public.memos enable row level security;

revoke all on table public.memos from anon;
revoke all on table public.memos from authenticated;

-- owner_id는 3단계 인증에서 사용하며 auth.users 외래키는 이 단계에서 만들지 않는다.
